name: SDK publish

on:
  push:
    branches:
      - 'master'
      - 'support/*'
    tags-ignore:
      - '**'

jobs:
  unit:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Update bundler
      run: gem install bundler

    - name: Install bundler dependencies
      run: bundle install

    - name: Generate unique device name
      run: echo "DEVICE_NAME=TestDevice_$(date +%Y%m%d%H%M%S)_$(uuidgen)" >> $GITHUB_ENV

    - name: Create new iOS simulator
      run: xcrun simctl create $DEVICE_NAME com.apple.CoreSimulator.SimDeviceType.iPhone-12 com.apple.CoreSimulator.SimRuntime.iOS-16-2

    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
      env:
        CI: true
        DEVICE_NAME: ${{ env.DEVICE_NAME }}

    - name: Delete iOS simulator
      run: xcrun simctl delete $DEVICE_NAME

  publish:
    needs: [unit]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Release generation
      run: ./git-release.sh "${{ github.event.head_commit.message }}" "${{secrets.GITHUBACCESSTOKEN}}" "${{secrets.GITHUBUSER}}"
    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
    - name: Run build
      run: bundle exec fastlane buildLane
      env:
        CI: true
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push Mindbox.podspec --allow-warnings
        pod trunk push MindboxNotifications.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
